Resources:
  SimpleEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t3.micro
      ImageId: ami-08bf489a05e916bbd  # Replace with a valid AMI ID for your region
      SubnetId: subnet-098f07ee4f34861f1
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MySimpleInstance  # Replace with your desired instance name
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y nginx
          systemctl start nginx
          systemctl enable nginx

          # Create a sample index.html file
          echo "<html>
          <head>
            <title>Welcome to Nginx on AWS</title>
          </head>
          <body>
            <h1>SAMPLE WEBPAGE Using CloudFormation</h1>
            <p>This is a sample webpage served by Nginx on an AWS EC2 instance.</p>
          </body>
          </html>" > /usr/share/nginx/html/index.html

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable HTTP access"
      VpcId: vpc-036e6c881e2cf03ed   # Specify your VPC ID here
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Allows HTTP access from anywhere (use with caution)

  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  EIPAssociation:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      InstanceId: !Ref SimpleEC2Instance
